## Ejercicios - NumPy 1

In [2]:
import numpy as np

In [3]:
# Versión
print(np.__version__)

1.26.4


### Ejercicio 1:
- Crea un vector con 10 elementos pares.

In [4]:
lista = []
for i in range(20):
    if i % 2 == 0:
        lista.append(i)

np.array(lista)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
lista = []
for i in range(2, 22, 2):
    lista.append(i)

np.array(lista)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
array_pares = np.array([i for i in range(2, 22, 2)])
array_pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Ejercicio 2:
- Obten el número de dimensiones y el tamaño del vector anterior.

In [7]:
array_pares.ndim

1

In [8]:
# numero de elementos en total
array_pares.size

10

In [9]:
# numero de elementos en cada dimension
array_pares.shape

(10,)

In [10]:
array_pares.dtype

dtype('int32')

In [11]:
array = np.array([10, 10, 20, 20, 30, 30])
array

array([10, 10, 20, 20, 30, 30])

In [12]:
array_acumulado = np.cumsum(array)
array_acumulado

array([ 10,  20,  40,  60,  90, 120])

In [13]:
np.diff(array_acumulado)

array([10, 20, 20, 30, 30])

In [14]:
# agregar el primero manualmente ya que no tiene ninguno delante para obtener el diff
original = np.insert(np.diff(array_acumulado), 0, array_acumulado[0])
original

array([10, 10, 20, 20, 30, 30])

### Ejercicio 3:
- Crea una lista con 5 números pares y otra lista con 5 números impares utilizando **list comprehension** y conviertelos en una matriz de (5, 2) dimensiones.

In [15]:
pares = np.array([i for i in range(2, 11, 2)])
pares

array([ 2,  4,  6,  8, 10])

In [16]:
impares = np.array([i for i in range(1, 11, 2)])
impares

array([1, 3, 5, 7, 9])

In [17]:
# concatenate y reshape. Por defecto es axis=0. Como es vector de 1 dimensión, axis 1 da error, no hay dos dimensiones
numbers = np.concatenate((pares, impares))
numbers

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [18]:
matriz_5x2 = numbers.reshape(5, 2)
matriz_5x2


array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

In [19]:
matriz_5x2.shape

(5, 2)

In [20]:
# lo aplana de 2 dimensiones a una dimensión:
matriz_5x2.flatten()

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [21]:
np.ravel(matriz_5x2)

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [22]:
# esto interesa si los datos son pareados, y están relacionados,
# Por ejemplo si queremos combinar elemento a elemento de un array city_consumption con road_consumption
np.column_stack((pares, impares))

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9]])

In [23]:
print(pares)
print(np.where(pares > 5))

[ 2  4  6  8 10]
(array([2, 3, 4], dtype=int64),)


In [24]:
indices = np.where(pares > 5) # devuelve los indices de los elementos que cumplen con la condiciones/es
pares[indices] # usamos los indices como filtros

array([ 6,  8, 10])

In [25]:
# en pandas
# filtro = df['price'] > 20
# df[filtro]

### Ejercicio 4:
- Obten el tipo de datos de la matriz anterior.

In [26]:
matriz_5x2.dtype

dtype('int32')

### Ejercicio 5:
- Crea una matriz de ceros de dimensión (4, 4) y remplaza los elementos de la diagonal principal por los números 5.

In [27]:
df_zeros =np.zeros((4,4))

In [28]:
df_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Ejercicio 6:
- Utiliza la función _**np.linspace()**_ para crear un vector con 10 elementos entre los números: -5 y 5.

In [29]:
df_five= np.linspace(-5, 5, 10)
df_five

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

### Ejercicio 7:
- Crea una matriz vacía de tamaño (3, 6) con elementos del tipo flotante.

In [30]:
df_float_empty = np.empty ((3, 6), dtype= np.float64)

print(df_float_empty)
print(df_float_empty.dtype)


[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.29061074e-306
  1.89146896e-307 7.56571288e-307]
 [4.00544531e-307 1.11261095e-306 3.56043054e-307 1.37961641e-306
  2.22518251e-306 1.33511969e-306]
 [6.23037657e-307 9.34609790e-307 8.45593934e-307 9.34600963e-307
  1.11261774e-306 6.23037657e-307]]
float64


### Ejercicio 8:
- Utiliza la matriz anterior para llenarla con números primos (investiga en internet una función que genere números primos e implementala).

In [31]:
def df_num_primos(n):
    
    if n < 2:
        return []
    
    primos = [True] * (n + 1)
    primos[0] = primos[1] = False 
    
    for i in range(2, int(n**0.5) + 1):
        if primos[i]:
            for j in range(i * i, n + 1, i):
                primos[j] = False
                
    return [x for x in range(n + 1) if primos[x]]

print(df_num_primos(62))


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61]


In [32]:
df_prim = np.array(df_num_primos(62)).reshape(3, 6)

print(df_prim)

[[ 2  3  5  7 11 13]
 [17 19 23 29 31 37]
 [41 43 47 53 59 61]]


### Ejercicio 9:
- Reemplaza los números de color azul por un 99 utilizando slicing.

$$\Large
\begin{bmatrix}
 1 &  2 &  \color{Blue}{3} &  4 \\
 5 &  \color{Blue}{6} &  7 &  \color{Blue}{8} \\
 \color{Blue}{9} & 10 & 11 & 12 \\
13 & 14 & \color{Blue}{15} & 16
\end{bmatrix}
$$

In [33]:
df_azul = np.arange(1, 17).reshape(4, 4)
print(df_azul)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [34]:

df_azul[[0,1,1,2,3],[2,1,3,0,2]] = 99
print(df_azul)

[[ 1  2 99  4]
 [ 5 99  7 99]
 [99 10 11 12]
 [13 14 99 16]]


### Ejercicio 10:
- Obten la primera y tercera fila de la matriz.

In [35]:
print(df_azul[0:1, [0, 1, 2, 3]])
print(df_azul[2:3, [0, 1, 2, 3]])


[[ 1  2 99  4]]
[[99 10 11 12]]


### Ejercico 11:
- Obten la tercera columna de la matriz.

In [36]:
print (df_azul[:, [2]])


[[99]
 [ 7]
 [11]
 [99]]


### Ejercicio 12:
- Obtener la segunda y tercera columna de la matriz.

In [37]:
print(df_azul[:,1:3])

[[ 2 99]
 [99  7]
 [10 11]
 [14 99]]


### Ejercicio 13:
- Obten una submatriz con los 4 números del centro.

In [38]:
df_azul = np.arange(1, 17).reshape(4, 4)
print(df_azul)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [39]:
print(df_azul[1:3, 1:3])

[[ 6  7]
 [10 11]]


### Ejercicio 14:
- Aplica la función _**np.flatten()**_ a la matriz anterior para obtener un vector.

In [40]:
df_flatten =df_azul.flatten()

print(df_flatten)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


### Ejercicio 15:
- Aplica el método _**.reshape()**_ al vector anterior para obtener una matriz de (1, 4) dimensiones.

In [41]:
#df_flatten.reshape(1, 4) no permite hacer reshape de 1 fila y 4 columnas
print= (df_flatten.reshape(4, 4))


### Ejercicio 16:
- Crea dos matrices de dimensión (4, 4) con números aleatorios y concatenalas verticalmente.

In [42]:
matriz_1= np.random.rand(4,4)
matriz_2= np.random.rand(4,4)

matriz_concatenada = np.vstack((matriz_1, matriz_2))

np.vstack((matriz_1, matriz_2))

array([[0.64444593, 0.28418614, 0.21746745, 0.02016009],
       [0.88266968, 0.55807043, 0.48049925, 0.37003771],
       [0.32912291, 0.73914501, 0.68072801, 0.12277313],
       [0.96292   , 0.98043513, 0.91668535, 0.1323405 ],
       [0.92761713, 0.63159204, 0.25157994, 0.03984856],
       [0.0085797 , 0.45097039, 0.02161239, 0.60607651],
       [0.92230374, 0.65841155, 0.20839352, 0.40477716],
       [0.0350047 , 0.20216537, 0.05822587, 0.20548705]])

################################################################################################################################